Repository ITZEEP/frontend, pull requests merged in 2025-08, with the labels that each got.

#60 [REFACTOR] 등기부 등본 OCR 결과 형식 수정
  src/apis/fraud.js
  src/components/common/BaseCheckbox.vue
  src/components/common/BaseModal.vue
  src/components/common/BaseSelect.vue
  src/components/common/CustomSelect.vue
  src/components/common/EmptyState.vue
  src/components/common/ErrorModal.vue
  src/components/common/ErrorState.vue
  src/components/common/ToggleRadio.vue
  src/components/icons/IconChevronDown.vue
  src/components/risk-check/DocumentUpload.vue
  src/components/risk-check/LoginRequiredModal.vue
  src/components/risk-check/PropertyCard.vue
  src/components/risk-check/PropertyInfoForm.vue
  src/components/risk-check/PropertyTypeSelector.vue
  src/components/risk-check/PropertyTypeWarningModal.vue
  src/components/risk-check/RiskCheckHistoryModal.vue
  src/components/risk-check/confirm/OCRFormField.vue
  src/components/risk-check/confirm/PropertyRegistrationForm.vue
  src/components/risk-check/result/DetailedAnalysis.vue
  src/components/risk-check/result/OverallRiskSection.vue
  src/components/risk-check/result/PropertyInfoCard.vue
  src/components/risk-check/result/RecommendedServices.vue
  src/pages/auth/SignupPage.vue
  src/pages/risk-check/RiskCheckConfirm.vue
  src/pages/risk-check/RiskCheckHome.vue
  src/pages/risk-check/RiskCheckResult.vue
  src/stores/fraud.js
Labels: ♻️ refactor

#67 [FEAT] 메인 헤더에 알람 드롭다운 구현
  package-lock.json
  package.json
  src/assets/icons/AlarmIcon.vue
  src/components/alarm/AlarmCard.vue
  src/components/alarm/AlarmDropdown.vue
  src/components/layouts/menu/AuthSection.vue
Labels: ✨ feature

#66 [FEAT] 임차인 계약전 API 연동
  src/apis/pre-contract-buyer.js
  src/components/pre-contract/buyer/step2/Step2.vue
  src/components/pre-contract/buyer/step2/Step2Risk.vue
  src/components/pre-contract/buyer/step2/Step2RiskCheck.vue
  src/components/pre-contract/buyer/step4/Step4ContractTerms.vue
  src/components/pre-contract/buyer/step4/Step4JeonseTerms.vue
  src/components/pre-contract/buyer/step4/Step4WolseTerms.vue
  src/components/pre-contract/buyer/step5/Step5Environment.vue
  src/components/pre-contract/buyer/step5/Step5Sub1MoveIn.vue
  src/components/pre-contract/buyer/step5/Step5Sub1MoveInPet.vue
  src/components/pre-contract/buyer/step5/Step5Sub2Residency.vue
  src/components/pre-contract/buyer/step6/Step6Confirm.vue
  src/pages/pre-contract/PreContractPage.vue
  src/stores/preContract.js
Labels: ✨ feature

#76 ♻ refactor: 필드명 변경, 체크박스 공통 컴포넌트 사용
  src/components/homes/homecreate/DealTypeSelector.vue
  src/components/homes/homecreate/HomeStructureSection.vue
  src/components/homes/homecreate/HouseTypeSelector.vue
  src/components/homes/homecreate/Step1BasicInfo.vue
  src/components/homes/homecreate/Step2PriceInfo.vue
  src/components/homes/homecreate/Step3DetailInfo.vue
  src/components/homes/homecreate/Step4ImageUpload.vue
  src/components/homes/homedetails/ListingBasicInfo.vue
  src/components/homes/homelist/FilterSidebar.vue
  src/components/homes/homelist/ListingCard.vue
  src/components/homes/homeupdate/FacilityInfoForm.vue
  src/components/homes/homeupdate/PriceInfoForm.vue
  src/components/homes/homeupdate/RoomInfoForm.vue
  src/pages/homes/HomeCreatePage.vue
  src/pages/homes/HomeDetailsPage.vue
  src/pages/homes/HomeListPage.vue
  src/pages/homes/HomeUpdatePage.vue
Labels: ♻️ refactor

#98 [FEAT] 위험도 체크 주소 입력 개선 및 홈 페이지 구현
  src/apis/chatApi.js
  src/apis/fraud.js
  src/components/chat/chatList/ChatList.vue
  src/components/chat/layout/ChatLayout.vue
  src/components/chat/layout/SideBar.vue
  src/components/mypage/fraud-analysis/FraudAnalysisCard.vue
  src/components/risk-check/PropertyInfoForm.vue
  src/components/risk-check/result/RecommendedServices.vue
  src/pages/HomePage.vue
  src/pages/chat/ChatPage.vue
  src/pages/mypage/MyPageFraudAnalysis.vue
  src/pages/risk-check/RiskCheckConfirm.vue
  src/pages/risk-check/RiskCheckResult.vue
Labels: ♻️ refactor, ✨ feature

#102 [FEAT] 업로드된 계약서 OCR 추출 후 MongoDB 저장 구현
  src/apis/preContractOwner.js
  src/components/common/BaseInput.vue
  src/components/pre-contract/owner/step5/Step5UploadTerms.vue
  src/components/pre-contract/owner/step5/TermsConfirmModal.vue
  src/components/pre-contract/owner/step5/UploadContractBox.vue
Labels: ✨ feature
